export interface Task {
  id: string;
  title: string;
  officer: string;
  assignedBy: string;
  assignedTo: string;
  status: 'In Progress' | 'Completed' | 'Pending' | 'Not Started';
  severity: 'Critical' | 'High' | 'Medium' | 'Low';
  location: string;
  assignedDate: string;
  assignedTime: string;
  deadline: string;
  deadlineTime: string;
  description: string;
  team: string;
}

export const tasks: Task[] =
  [
    {
      id: '1',
      title: 'Downtown Area Patrol',
      officer: 'Officer Johnson',
      assignedBy: 'Sgt. Williams',
      assignedTo: 'Officer Johnson',
      status: 'In Progress',
      severity: 'High',
      location: 'Downtown District',
      assignedDate: '2025-06-28',
      assignedTime: '08:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '08:00 PM',
      description: 'Regular patrol of downtown area with focus on high-traffic zones',
      team: 'Patrol Unit A'
    },
    {
      id: '2',
      title: 'Highway Traffic Monitoring',
      officer: 'Officer Smith',
      assignedBy: 'Lt. Davis',
      assignedTo: 'Officer Smith',
      status: 'Completed',
      severity: 'Medium',
      location: 'Highway 101',
      assignedDate: '2025-06-28',
      assignedTime: '06:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '02:00 PM',
      description: 'Monitor traffic flow and respond to incidents on Highway 101',
      team: 'Traffic Division'
    },
    {
      id: '3',
      title: 'Investigation Follow-up',
      officer: 'Officer Brown',
      assignedBy: 'Det. Miller',
      assignedTo: 'Officer Brown',
      status: 'Pending',
      severity: 'Critical',
      location: 'West Side',
      assignedDate: '2025-06-28',
      assignedTime: '10:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '06:00 PM',
      description: 'Follow up on robbery case - interview witnesses',
      team: 'Detective Unit'
    },
    {
      id: '4',
      title: 'Evidence Collection',
      officer: 'Officer Wilson',
      assignedBy: 'Dr. Anderson',
      assignedTo: 'Officer Wilson',
      status: 'In Progress',
      severity: 'Critical',
      location: 'Crime Scene Alpha',
      assignedDate: '2025-06-27',
      assignedTime: '09:30 AM',
      deadline: '2025-06-28',
      deadlineTime: '11:00 AM',
      description: 'Collect and document evidence from crime scene',
      team: 'Forensics'
    },
    {
      id: '5',
      title: 'Mall Security Patrol',
      officer: 'Officer Martinez',
      assignedBy: 'Sgt. Rodriguez',
      assignedTo: 'Officer Martinez',
      status: 'Completed',
      severity: 'Medium',
      location: 'Shopping Mall',
      assignedDate: '2025-06-27',
      assignedTime: '07:00 AM',
      deadline: '2025-06-27',
      deadlineTime: '07:00 PM',
      description: 'Patrol shopping district and ensure public safety',
      team: 'Patrol Unit B'
    },
    {
      id: '6',
      title: 'Community Outreach Event',
      officer: 'Officer Garcia',
      assignedBy: 'Capt. Taylor',
      assignedTo: 'Officer Garcia',
      status: 'Not Started',
      severity: 'Low',
      location: 'Community Center',
      assignedDate: '2025-06-27',
      assignedTime: '02:00 PM',
      deadline: '2025-06-29',
      deadlineTime: '04:00 PM',
      description: 'Participate in community safety awareness program',
      team: 'Community Relations'
    },
    {
      id: '7',
      title: 'Bank Security Check',
      officer: 'Officer Thompson',
      assignedBy: 'Lt. Harris',
      assignedTo: 'Officer Thompson',
      status: 'Completed',
      severity: 'High',
      location: 'First National Bank',
      assignedDate: '2025-06-26',
      assignedTime: '11:00 AM',
      deadline: '2025-06-26',
      deadlineTime: '11:30 AM',
      description: 'Routine security inspection and protocol review',
      team: 'Special Operations'
    },
    {
      id: '8',
      title: 'School Safety Patrol',
      officer: 'Officer Lee',
      assignedBy: 'Sgt. Johnson',
      assignedTo: 'Officer Lee',
      status: 'Completed',
      severity: 'Medium',
      location: 'Lincoln Elementary',
      assignedDate: '2025-06-26',
      assignedTime: '07:30 AM',
      deadline: '2025-06-26',
      deadlineTime: '04:30 PM',
      description: 'Ensure student safety during school hours',
      team: 'School Resource Unit'
    },
    {
      id: '9',
      title: 'Night Patrol',
      officer: 'Officer Adams',
      assignedBy: 'Sgt. Carter',
      assignedTo: 'Officer Adams',
      status: 'In Progress',
      severity: 'High',
      location: 'East District',
      assignedDate: '2025-06-28',
      assignedTime: '10:00 PM',
      deadline: '2025-06-29',
      deadlineTime: '06:00 AM',
      description: 'Night patrol in high-crime areas',
      team: 'Patrol Unit C'
    },
    {
      id: '10',
      title: 'Traffic Stop Training',
      officer: 'Officer Clark',
      assignedBy: 'Lt. Thompson',
      assignedTo: 'Officer Clark',
      status: 'Not Started',
      severity: 'Low',
      location: 'Training Facility',
      assignedDate: '2025-06-27',
      assignedTime: '09:00 AM',
      deadline: '2025-06-27',
      deadlineTime: '12:00 PM',
      description: 'Conduct traffic stop procedure training',
      team: 'Training Division'
    },
    {
      id: '11',
      title: 'Drug Bust Surveillance',
      officer: 'Officer Evans',
      assignedBy: 'Det. Brooks',
      assignedTo: 'Officer Evans',
      status: 'Pending',
      severity: 'Critical',
      location: 'North Side',
      assignedDate: '2025-06-26',
      assignedTime: '03:00 PM',
      deadline: '2025-06-27',
      deadlineTime: '03:00 AM',
      description: 'Monitor suspected drug activity',
      team: 'Narcotics Unit'
    },
    {
      id: '12',
      title: 'Crowd Control',
      officer: 'Officer Walker',
      assignedBy: 'Capt. Lewis',
      assignedTo: 'Officer Walker',
      status: 'Completed',
      severity: 'Medium',
      location: 'City Square',
      assignedDate: '2025-06-25',
      assignedTime: '05:00 PM',
      deadline: '2025-06-25',
      deadlineTime: '11:00 PM',
      description: 'Manage crowd at public event',
      team: 'Riot Control'
    },
    {
      id: '13',
      title: 'VIP Escort',
      officer: 'Officer Young',
      assignedBy: 'Lt. King',
      assignedTo: 'Officer Young',
      status: 'In Progress',
      severity: 'High',
      location: 'City Hall',
      assignedDate: '2025-06-28',
      assignedTime: '11:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '03:00 PM',
      description: 'Provide security escort for VIP',
      team: 'Special Operations'
    },
    {
      id: '14',
      title: 'Burglary Investigation',
      officer: 'Officer Scott',
      assignedBy: 'Det. White',
      assignedTo: 'Officer Scott',
      status: 'Pending',
      severity: 'Medium',
      location: 'South Residential',
      assignedDate: '2025-06-27',
      assignedTime: '08:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '05:00 PM',
      description: 'Investigate reported burglary cases',
      team: 'Detective Unit'
    },
    {
      id: '15',
      title: 'Traffic Accident Response',
      officer: 'Officer Green',
      assignedBy: 'Sgt. Hall',
      assignedTo: 'Officer Green',
      status: 'Completed',
      severity: 'High',
      location: 'Highway 52',
      assignedDate: '2025-06-26',
      assignedTime: '02:00 PM',
      deadline: '2025-06-26',
      deadlineTime: '06:00 PM',
      description: 'Respond to multi-vehicle accident',
      team: 'Traffic Division'
    },
    {
      id: '16',
      title: 'Community Safety Workshop',
      officer: 'Officer Allen',
      assignedBy: 'Capt. Moore',
      assignedTo: 'Officer Allen',
      status: 'Not Started',
      severity: 'Low',
      location: 'Public Library',
      assignedDate: '2025-06-29',
      assignedTime: '10:00 AM',
      deadline: '2025-06-29',
      deadlineTime: '02:00 PM',
      description: 'Lead safety workshop for residents',
      team: 'Community Relations'
    },
    {
      id: '17',
      title: 'Evidence Analysis',
      officer: 'Officer Turner',
      assignedBy: 'Dr. Parker',
      assignedTo: 'Officer Turner',
      status: 'In Progress',
      severity: 'Critical',
      location: 'Forensic Lab',
      assignedDate: '2025-06-27',
      assignedTime: '09:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '09:00 PM',
      description: 'Analyze collected evidence from crime scene',
      team: 'Forensics'
    },
    {
      id: '18',
      title: 'School Crossing Duty',
      officer: 'Officer Wright',
      assignedBy: 'Sgt. Nelson',
      assignedTo: 'Officer Wright',
      status: 'Completed',
      severity: 'Medium',
      location: 'West Elementary',
      assignedDate: '2025-06-25',
      assignedTime: '07:00 AM',
      deadline: '2025-06-25',
      deadlineTime: '09:00 AM',
      description: 'Ensure safe crossing for students',
      team: 'School Resource Unit'
    },
    {
      id: '19',
      title: 'Drug Awareness Program',
      officer: 'Officer Hill',
      assignedBy: 'Capt. Young',
      assignedTo: 'Officer Hill',
      status: 'Not Started',
      severity: 'Low',
      location: 'High School',
      assignedDate: '2025-06-30',
      assignedTime: '01:00 PM',
      deadline: '2025-06-30',
      deadlineTime: '03:00 PM',
      description: 'Conduct drug awareness session for students',
      team: 'Community Relations'
    },
    {
      id: '20',
      title: 'Parking Enforcement',
      officer: 'Officer Baker',
      assignedBy: 'Sgt. Cook',
      assignedTo: 'Officer Baker',
      status: 'Completed',
      severity: 'Low',
      location: 'Downtown Parking',
      assignedDate: '2025-06-28',
      assignedTime: '09:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '05:00 PM',
      description: 'Enforce parking regulations in downtown area',
      team: 'Traffic Division'
    },
    {
      id: '21',
      title: 'Stakeout Operation',
      officer: 'Officer Carter',
      assignedBy: 'Det. Stewart',
      assignedTo: 'Officer Carter',
      status: 'In Progress',
      severity: 'Critical',
      location: 'Industrial Zone',
      assignedDate: '2025-06-27',
      assignedTime: '11:00 PM',
      deadline: '2025-06-28',
      deadlineTime: '07:00 AM',
      description: 'Conduct stakeout for suspected illegal activity',
      team: 'Narcotics Unit'
    },
    {
      id: '22',
      title: 'Event Security',
      officer: 'Officer Reed',
      assignedBy: 'Lt. Perry',
      assignedTo: 'Officer Reed',
      status: 'Pending',
      severity: 'High',
      location: 'City Stadium',
      assignedDate: '2025-06-29',
      assignedTime: '04:00 PM',
      deadline: '2025-06-29',
      deadlineTime: '10:00 PM',
      description: 'Provide security for sports event',
      team: 'Special Operations'
    },
    {
      id: '23',
      title: 'Traffic Signal Check',
      officer: 'Officer Morgan',
      assignedBy: 'Sgt. Hayes',
      assignedTo: 'Officer Morgan',
      status: 'Completed',
      severity: 'Medium',
      location: 'Main Street',
      assignedDate: '2025-06-26',
      assignedTime: '08:00 AM',
      deadline: '2025-06-26',
      deadlineTime: '12:00 PM',
      description: 'Inspect and report on traffic signal functionality',
      team: 'Traffic Division'
    },
    {
      id: '24',
      title: 'Witness Interview',
      officer: 'Officer Foster',
      assignedBy: 'Det. Coleman',
      assignedTo: 'Officer Foster',
      status: 'Pending',
      severity: 'High',
      location: 'Police Station',
      assignedDate: '2025-06-28',
      assignedTime: '02:00 PM',
      deadline: '2025-06-28',
      deadlineTime: '05:00 PM',
      description: 'Interview key witness for ongoing case',
      team: 'Detective Unit'
    },
    {
      id: '25',
      title: 'Public Park Patrol',
      officer: 'Officer Russell',
      assignedBy: 'Sgt. Bryant',
      assignedTo: 'Officer Russell',
      status: 'In Progress',
      severity: 'Medium',
      location: 'Central Park',
      assignedDate: '2025-06-28',
      assignedTime: '10:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '06:00 PM',
      description: 'Patrol public park to ensure safety',
      team: 'Patrol Unit A'
    },
    {
      id: '26',
      title: 'Firearms Training',
      officer: 'Officer Jenkins',
      assignedBy: 'Lt. Sullivan',
      assignedTo: 'Officer Jenkins',
      status: 'Not Started',
      severity: 'Low',
      location: 'Shooting Range',
      assignedDate: '2025-06-30',
      assignedTime: '09:00 AM',
      deadline: '2025-06-30',
      deadlineTime: '12:00 PM',
      description: 'Attend mandatory firearms training session',
      team: 'Training Division'
    },
    {
      id: '27',
      title: 'Traffic Camera Review',
      officer: 'Officer Murray',
      assignedBy: 'Sgt. Webb',
      assignedTo: 'Officer Murray',
      status: 'Completed',
      severity: 'Medium',
      location: 'Control Room',
      assignedDate: '2025-06-27',
      assignedTime: '01:00 PM',
      deadline: '2025-06-27',
      deadlineTime: '04:00 PM',
      description: 'Review traffic camera footage for violations',
      team: 'Traffic Division'
    },
    {
      id: '28',
      title: 'Missing Person Search',
      officer: 'Officer Hart',
      assignedBy: 'Det. Ford',
      assignedTo: 'Officer Hart',
      status: 'In Progress',
      severity: 'Critical',
      location: 'East Side',
      assignedDate: '2025-06-28',
      assignedTime: '07:00 AM',
      deadline: '2025-06-28',
      deadlineTime: '07:00 PM',
      description: 'Coordinate search for missing person',
      team: 'Detective Unit'
    },
    {
      id: '29',
      title: 'School Safety Drill',
      officer: 'Officer Dixon',
      assignedBy: 'Sgt. Shaw',
      assignedTo: 'Officer Dixon',
      status: 'Completed',
      severity: 'Medium',
      location: 'North High School',
      assignedDate: '2025-06-26',
      assignedTime: '10:00 AM',
      deadline: '2025-06-26',
      deadlineTime: '02:00 PM',
      description: 'Conduct safety drill with school staff',
      team: 'School Resource Unit'
    },
    {
      id: '30',
      title: 'Community Watch Meeting',
      officer: 'Officer Burns',
      assignedBy: 'Capt. Elliott',
      assignedTo: 'Officer Burns',
      status: 'Not Started',
      location: 'North High School',
      severity: 'Low',
      assignedDate: '2025-06-29',
      assignedTime: '06:00 PM',
      deadline: '2025-06-29',
      deadlineTime: '08:00 PM',
      description: 'Attend community watch meeting',
      team: 'Community Relations'
    },
  ]
